### ISSUE TITLE
Keyboard shortcut support

### ISSUE THREAD

**Issue by null-dev** [null-dev/firefox-profile-switcher#1]

**Comment by cupcakearmy** [comment]
Yes please! Maybe `Ctrl + Shift + M` / `Cmd + Shift + M` to be consistent with chrome?

**Comment by fazlerabbi37** [comment]
anyone working on this? If not, I would like to take a jab at it :sweat_smile:

**Comment by null-dev** [comment]
> anyone working on this? If not, I would like to take a jab at it sweat_smile

I'm currently not working on this as I'm still trying to stabilize profile switching (still isn't perfect yet). If you would like to work on this though, I'd recommend using https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands as it lets users customize the shortcuts without having to write your own UI to do that.

**Comment by fazlerabbi37** [comment]
cool! I will get started :ok_hand: 

> I'd recommend using https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands 

thanks a ton for the pointer! :pray:

**Comment by fazlerabbi37** [comment]
PR for this issue: #19

**Comment by cupcakearmy** [comment]
> PR for this issue: #19

Amazing ❤️  Is there a reason you did not choose the default key mappings of chrome?

**Comment by fazlerabbi37** [comment]
> Is there a reason you did not choose the default key mappings of chrome?

actually, yes. while I would have liked that too but the default key mappings of chrome (Ctrl+Shit+m) opens [Responsive Design Mode](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode) on Firefox. :cry:

**Comment by cupcakearmy** [comment]
Ah ok, I'm on macOS so it's different here. Makes sense :)

**Comment by null-dev** [comment]
Fixed in newest release!

**Comment by johndevedu** [comment]
On Mac, I couldn't get this to work using `Cmd + Alt + U`. I also tried `Ctrl + Alt + U`. It looks like there's a conflict with a built-in Firefox shortcut. I was able to find a document for the user to change the shortcut: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox. I changed it to `Ctrl + Shift + M` / `Cmd + Shift + M` and it works!
