### ISSUE TITLE
can't reassign default profile

### ISSUE THREAD

**Issue by justin-hackin** [null-dev/firefox-profile-switcher#10]
Reproduction: Manage profiles-> Edit profiles -> select non-default -> click "Set to default" 

Result: Firefox alert box containing message "ERROR: editingProfileSave is not defined"

Firefox version: 89.0.2 (64-bit)
Extension version: 1.1.2

Otherwise this extension is GREAT. I can't believe this feature isn't a part of Firefox, thanks so much for making this!

**Comment by justin-hackin** [comment]
@null-dev  might there be a workaround for this? Like editing a config file or running a command via the installed app?

**Comment by null-dev** [comment]
You can edit your `profiles.ini` file (http://kb.mozillazine.org/Profiles.ini_file). This is a pretty critical issue though so I'll push out a fix for it this weekend.

**Comment by justin-hackin** [comment]
Thanks for offering to address this quickly and for offering a workaround. It seemed to work but I noticed the extension still thinks the non-default profile is the default. I also noticed there's a `StartWithLastProfile` option and I'm wondering if this behaviour should be an option in the extension. When I changed it to 0 I got a dialog asking me which profile I want to be default when I opened Firefox again and the value was re-set to 1 after I chose.

**Comment by null-dev** [comment]
The new version is released and should fix the issue. I did in fact think about including the StartWithLastProfile option however when you use it it opens its' own profile manager window. There's a couple caveats if a user creates a profile using that window though (e.g. the extension won't get auto-installed in the new profile and they won't be able to choose a profile picture).

So to discourage users from using that window I didn't add the option in the switcher.
