### ISSUE TITLE
After executing all commands it still says setup incomplete (mac)

### ISSUE THREAD

**Issue by cwesterink** [null-dev/firefox-profile-switcher#11]
After executing all commands it still says setup incomplete (mac)

**Comment by null-dev** [comment]
I just released a new version of the extension that should hopefully fix this issue. Can you try updating to it? Also make sure to update the additional software when asked.

**Comment by caseykramer** [comment]
I'm seeing the same issue on mac with the latest version of extension and connector (installed today 14/7/2021). 

firefox-profile-switcher-connector v0.0.8
extension v1.1.5 (updated 14/7/2021)

**Comment by cwesterink** [comment]
I removed the addon and followed the installation instructions. Instead of just updating it.
It works for me now. 

Thank You

**Comment by null-dev** [comment]
@caseykramer Can you post what happens when you run each of the following commands?

- `cat ~"/Library/Application Support/Mozilla/NativeMessagingHosts/ax.nd.profile_switcher_ff.json"`
- `find /usr/local/Cellar/firefox-profile-switcher-connector`
- `echo | ff-pswitch-connector`
- `brew config`

**Comment by billybullock** [comment]
I'm not @caseykramer but I did just try running the installation by following the instructions and the extension is still saying incomplete setup. I've also restarted Firefox. The output of the above commands are below and it seems Xcode isn't being installed. Is this something I need to do separately?

Thank you!

BB-Work-MacBook-Air:~ billy$ cat ~"/Library/Application Support/Mozilla/NativeMessagingHosts/ax.nd.profile_switcher_ff.json"
{
    "allowed_extensions": [
        "profile-switcher-ff@nd.ax"
    ],
    "description": "Profile Switcher for Firefox",
    "name": "ax.nd.profile_switcher_ff",
    "path": "/usr/local/Cellar/firefox-profile-switcher-connector/0.0.8/bin/ff-pswitch-connector",
    "type": "stdio"
}

BB-Work-MacBook-Air:~ billy$ find /usr/local/Cellar/firefox-profile-switcher-connector
/usr/local/Cellar/firefox-profile-switcher-connector
/usr/local/Cellar/firefox-profile-switcher-connector/0.0.8
/usr/local/Cellar/firefox-profile-switcher-connector/0.0.8/INSTALL_RECEIPT.json
/usr/local/Cellar/firefox-profile-switcher-connector/0.0.8/bin
/usr/local/Cellar/firefox-profile-switcher-connector/0.0.8/bin/ff-pswitch-connector
/usr/local/Cellar/firefox-profile-switcher-connector/0.0.8/.brew
/usr/local/Cellar/firefox-profile-switcher-connector/0.0.8/.brew/firefox-profile-switcher-connector.rb
/usr/local/Cellar/firefox-profile-switcher-connector/0.0.8/README.md
/usr/local/Cellar/firefox-profile-switcher-connector/0.0.8/ax.nd.profile_switcher_ff.json
/usr/local/Cellar/firefox-profile-switcher-connector/0.0.8/LICENSE.txt

BB-Work-MacBook-Air:~ billy$ echo | ff-pswitch-connector
C{"id":-1,"resp":{"event":"ConnectorInformation","version":"0.0.8"}}thread 'main' panicked at 'Failed to read native message size!: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }', src/native_req.rs:66:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

BB-Work-MacBook-Air:~ billy$ brew config
HOMEBREW_VERSION: 3.2.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7d37d09709b6fbd5b89b468eb0b4438ffa0fb81c
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5dd9c085fdaff68305e3370f91cc3d7d6e6c04a0
Core tap last commit: 39 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 10.0.1 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A

BB-Work-MacBook-Air:~ billy$

**Comment by null-dev** [comment]
@billybullock Thanks for the info, unfortunately everything looks fine and I still have no idea why the extension isn't running on Macs. Can you try running the command in this comment? https://github.com/null-dev/firefox-profile-switcher-connector/issues/5#issuecomment-880148539

**Comment by billybullock** [comment]
@null-dev Here is the output from the command.

BB-Work-MacBook-Air:~ billy$ sudo ln -s /usr/local/Cellar/firefox-profile-switcher-connector/0.0.8/ax.nd.profile_switcher_ff.json /Library/Application Support/Mozilla/NativeMessagingHosts/ax.nd.profile_switcher_ff.json
Password:
ln: Support/Mozilla/NativeMessagingHosts/ax.nd.profile_switcher_ff.json: No such file or directory
BB-Work-MacBook-Air:~ billy$

**Comment by billybullock** [comment]
Got it working my copying "/usr/local/Cellar/firefox-profile-switcher-connector/0.0.8/ax.nd.profile_switcher_ff.json" to "/Library/Application Support/Mozilla/NativeMessagingHosts/" where this file was missing. Restarted Firefox and it's now working. Many thanks for your replies and work on this extension!

**Comment by null-dev** [comment]
@billybullock Whoops yeah I forgot some quotes in my command, nice job figuring it out! Since it seems to work I'm going to close this issue now. Just to repeat it for others, running the following command seems to solve the issue:

```
sudo mkdir -p "/Library/Application Support/Mozilla/NativeMessagingHosts"
sudo ln -sf /usr/local/Cellar/firefox-profile-switcher-connector/0.0.8/ax.nd.profile_switcher_ff.json "/Library/Application Support/Mozilla/NativeMessagingHosts/ax.nd.profile_switcher_ff.json"
```
