### ISSUE TITLE
Broke tmux (mac)

### ISSUE THREAD

**Issue by Zigrino** [null-dev/firefox-profile-switcher#12]
After following the process for installing, when I try to use tmux, instead of launching it gives me this error: 
^[[>0;95;0c^[P>|iTerm2 3.4.8^[\[exited]

do you know how I can fix this?

**Comment by null-dev** [comment]
I'm not sure how this can happen as the extension doesn't interact with tmux. Perhaps it's caused by brew? Did you have to install brew or did you already have it installed?

**Comment by Zigrino** [comment]
Yeah, I had tmux installed through home brew. I fixed it though, I think I
had to delete all the tmux sessions because the extension was messing with
that. Thanks though!

**Comment by null-dev** [comment]
Alright, glad to see you have it resolved, sorry for the slow response!
