### ISSUE TITLE
Activate browser window when selected profile is already open in one

### ISSUE THREAD

**Issue by hschmidt** [null-dev/firefox-profile-switcher#13]
When switching to a profile, would it be possible to activate the respective browser window if there's already one open with the selected profile? On my system, the current version of this extension does nothing in that case. When there is no window for the selected profile, this extension correctly opens a new window but it doesn't switch to an already open one.

**Comment by null-dev** [comment]
This was already implemented but due to some bugs it didn't work reliably. I've recently pushed out an update that should have stabilized things. If you've updated both the extension and the native software and still find that it still doesn't work properly feel free to re-open this issue.
