### ISSUE TITLE
Compatibility with MSIX (Microsoft Store) version?

### ISSUE THREAD

**Issue by asimovitsch** [null-dev/firefox-profile-switcher#16]
I don't know if this even deserves to be reported, but anyway.

I wanted to run the profile switcher on the Microsoft Store version of Firefox. Profile creation seems to work if I am reading my profiles.ini under C:\Users\{username}\AppData\Roaming\Mozilla\Firefox correctly. However, when I click on the new profile, nothing happens.

Could this have anything to do with the new location of the executable (C:\Program Files\WindowsApps\Mozilla.Firefox_94.0.1.0_x64__n80bbvh6b1yt2\VFS\ProgramFiles\Firefox Package Root)? I don't realy know how exactly the extension operates, so I may be completely off-base here.

**Comment by ahmed-abdelrazek** [comment]
the extension doesn't see the installed rust program `Profile Switcher for Firefox Native Connector`

also the profile path changed to something like ` C:\Users\{user name}\AppData\Local\Packages\Mozilla.Firefox_n80bbvh6b1yt2\LocalCache\Roaming\Mozilla\Firefox\Profiles\bebxluk9.default-release`

**Comment by null-dev** [comment]
Thanks for the report @asimovitsch and @ahmed-abdelrazek!

I've published a new version of the connector software that should work with the Microsoft Store version of Firefox, you can download it here: https://github.com/null-dev/firefox-profile-switcher-connector/releases/tag/v0.1.0. If you still have problems feel free to re-open the issue.
