### ISSUE TITLE
BitDefender reporting Malware in dowload for plugin

### ISSUE THREAD

**Issue by bct-drew** [null-dev/firefox-profile-switcher#17]
BitDefender reports malware Gen:Variant.Razy.985422 is present in the file the plugin has you download to complete setup.

**Comment by tranquilknight** [comment]
Same here. Seeing Gen:Variant.Razy.985422 (B) while scanning with Emsisoft Emergency Kit. I think it uses BitDefender definitions.

**Comment by null-dev** [comment]
I just made a new release to fix an unrelated bug but after uploading it to VirusTotal it's now marked as clean so I'm going to assume this was just a one-off issue. If it's still being detected as malware for you, please re-open the issue.
