### ISSUE TITLE
Not working on Firefox Developer Edition

### ISSUE THREAD

**Issue by ManuelV3G4** [null-dev/firefox-profile-switcher#21]

**Comment by null-dev** [comment]
Are you able to get past the "Complete Setup" step?

**Comment by ManuelV3G4** [comment]
Yes, I complete the entire setup

**Comment by null-dev** [comment]
Are you getting any errors? What do you mean by "not working"?

**Comment by antdking** [comment]
Working fine for firefox dev 99.0b8 on Manjaro with your binary distribution here.

Perhaps an issue in the past that is since resolved.
