### ISSUE TITLE
Add more information on installation on Mac

### ISSUE THREAD

**Issue by sethigoldy** [null-dev/firefox-profile-switcher#22]
Hey

Just a suggestion on adding more info around `how to install on Mac` page, please add the following lines or something similar:

If even after installing the `firefox-profile-switcher-connector` the extension is still not linked, run the following commands
```
sudo mkdir -p "/Library/Application Support/Mozilla/NativeMessagingHosts"
sudo ln -sf "/usr/local/Cellar/firefox-profile-switcher-connector/0.0.9/ax.nd.profile_switcher_ff.json" "/Library/Application Support/Mozilla/NativeMessagingHosts"/ax.nd.profile_switcher_ff.json
```

BTW I know this shows after installing for the first time but when upgrading the backend via `brew upgrade firefox-profile-switcher-connector`, its better to show the same in there as well. 

Thanks

**Comment by null-dev** [comment]
Added in latest release, thanks for the suggestion!
