### ISSUE TITLE
Cant complete the setup

### ISSUE THREAD

**Issue by jimmyw** [null-dev/firefox-profile-switcher#3]
This plugin says my setup is complete, and there is an option to complete the setup, but the button does nothing.

Using Firefox 87.0 on OSX.

**Comment by jjb2019** [comment]
Same problem here. Windows 10, FF 87

**Comment by null-dev** [comment]
Hmm, there could be a popup blocker that's blocking the page from opening. I know of any other reason why the setup would be bugging like that.

You can visit the setup page manually here to finish the setup: https://github.com/null-dev/firefox-profile-switcher-connector/wiki/Download-connector-software

**Comment by jimmyw** [comment]
Yes, you are correct. Its a popup blocker that made the page not open.
