### ISSUE TITLE
Not working on Ubuntu 22

### ISSUE THREAD

**Issue by Win-Lawson** [null-dev/firefox-profile-switcher#31]
After updating to Ubuntu 22 this extension no longer works, I tried reinstalling firefox, but when I click on a second profile nothing happens.

**Comment by ajoy39** [comment]
Same issue here, profile switcher extension says the system software isn't installed but when I try to install it, it's already installed

**Comment by Win-Lawson** [comment]
> Same issue here, profile switcher extension says the system software isn't installed but when I try to install it, it's already installed

Exact same behavior I was having. In the meantime I've created two separate .desktop files for my desperate profiles, and moved these to the applications directory. Definitely harder to setup like this if you're a beginner but it is as functional if not more convenient then this extension

**Comment by Thomvh** [comment]
This is because in Ubuntu 22.04 Firefox runs in Snap. I do not think the Flatpak install method is compatible with this either. So we will have to wait for Null-dev to fix the issue.

**Comment by null-dev** [comment]
Update: currently looking into this but I am in the middle of moving right now so I am busy.

**Comment by null-dev** [comment]
I've added installation instructions for snap in version 1.3.1 of the extension (which is still pending approval). If it still doesn't work even with the new installation instructions, feel free to re-open the issue.
