### ISSUE TITLE
Instalation failed

### ISSUE THREAD

**Issue by LongJohn-Silver** [null-dev/firefox-profile-switcher#4]
When I try to install the connector software for Linux (64-bit, deb) it gives me an error.
It says:

`The following packages have unmet dependencies: ff-pswitch-connector: Depends: libc6 (>=2.31) but 2.27-3ubuntu1.4 is to be installed.`

I am using elementaryOS Hera 5.1.7 which is based on Ubuntu 18.04.4 LTS.

**Comment by null-dev** [comment]
Whoops, this should be fixed in v0.0.6 of the connector software (https://github.com/null-dev/firefox-profile-switcher-connector/releases/tag/v0.0.6).

Please re-open if it still doesn't work.

**Comment by LongJohn-Silver** [comment]
@null-dev Yup, it is fixed! Thanks a lot!
