### ISSUE TITLE
Windows : Works only on the default folder

### ISSUE THREAD

**Issue by Guibol22** [null-dev/firefox-profile-switcher#7]
On Windows, the extension works on a profile created in the default folder: C: \ Users \ XXX \ AppData \ Roaming \ Mozilla \ Firefox \ Profiles \
But it doesn't work if the profile is created in another folder. All my profiles are on another folder ...

**Comment by null-dev** [comment]
I can't replicate this issue. Did you move your entire browser storage folder (`C:\Users\XXX\AppData\Roaming\Mozilla\Firefox`) or just the profiles?

Also, can you send me your `profiles.ini` file? It should be located in the browser storage folder: `C:\Users\XXX\AppData\Roaming\Mozilla\Firefox\profiles.ini`.

**Comment by Guibol22** [comment]
Just the profiles (on another disk partition)

**Comment by null-dev** [comment]
I think I've finally managed to fix this issue in the latest release of the external software: https://github.com/null-dev/firefox-profile-switcher-connector/releases/download/v0.1.1/windows-x64.msi. I'm going to close this issue now but feel free to re-open it if it is still not working.
