### ISSUE TITLE
Can't open profiles with the extension on Arch Linux

### ISSUE THREAD

**Issue by pato-pan** [null-dev/firefox-profile-switcher#86]
The error I get on the extension's console is 
```
Got native response in: 4ms. native.js:118:21
Native error! 
Object { success: false, error: "The version of your browser that is currently running can no longer be found. This is usually because your browser has updated but you haven't restarted your browser recently to apply the update. Please restart your browser to resolve this issue.", debug_msg: null }
native.js:123:25
    reqId moz-extension://a7918ee6-6b55-4592-8962-51e6675b6c54/js/native.js:123
    initNativePort moz-extension://a7918ee6-6b55-4592-8962-51e6675b6c54/js/native.js:37
Internal native request error! 
Object { message: "The version of your browser that is currently running can no longer be found. This is usually because your browser has updated but you haven't restarted your browser recently to apply the update. Please restart your browser to resolve this issue." }
native.js:85:29
Uncaught (in promise) 
Object { message: "The version of your browser that is currently running can no longer be found. This is usually because your browser has updated but you haven't restarted your browser recently to apply the update. Please restart your browser to resolve this issue." }
```

My browser is up to date. Version 118.0 in 9/28/2023. I had restarted the browser with no effect.
Looking at the code, I don't understand the error. I don't understand where the extension is looking to obtain the browser version
This may have something to do with my browser not being installed in the default directory for my distro. It's installed on a custom location.

I think this issue could be tied to the native connector instead

**Comment by atomjack** [comment]
@pato-pan I came across a similar issue due to the connector not knowing where to find the firefox binary, although I don't have mine installed in a custom location. I found [this connector issue](https://github.com/null-dev/firefox-profile-switcher-connector/issues/14); after adding a config.json file to ~/.config/firefoxprofileswitcher/, and restarting my browser, the extension works just fine. So I bet you if you do that and specify your custom location, that may fix the issue.

**Comment by pato-pan** [comment]
I guess, but I am not interested in using this extension anymore. I'll assume that if I try what you suggested it would work, and I'll reopen if I try it one day and it doesn't work for me or someone else can reopen if they face the same issue. (If you can't reopen, give me a negative reaction or message me and I will reopen it)
