### ISSUE TITLE
Pressing "Complete Setup" does nothing

### ISSUE THREAD

**Issue by jsparber** [null-dev/firefox-profile-switcher#9]
Not sure if this problem come from running the flatpaked version of Firefox. When clicking the "Complete Setup" button from the popover nothing happens.

firefox-profile-switcher: 1.0.6
Firefox: 89.0 (64-bit) from [flathub](https://flathub.org/apps/details/org.mozilla.firefox)
Fedora Silverblue: 34.20210613.0

**Comment by jsparber** [comment]
Building the connector (inside flatpak for correct paths) and copying into the profile folder at the correct location worked.

**Comment by MarvelousMari** [comment]
Would you please describe how you built the connectors, and where the correct location is? I'm running into the same issue using flatpak

**Comment by snakyjake1** [comment]
I have a similar issue, but on Windows.
I have installed the exe file.
I have the Firefox addon installed.
I use Firefox portable.

**Comment by JoanEliot** [comment]
Likewise for me on Firefox Portable (Windows 10), the extension continues to report "Setup incomplete!" after installation of the connector and restarting the browser. It doesn't work.

**Comment by Yahya-Zekry** [comment]
> I have the same problem in Windows 10. Looks like it tries to load my profiles every few seconds but still shows Setup Incomplete. I tried to take a screenshot because this "loading" shows just for a few milliseconds and then shows default "Setup Incomplete" message most of the time http://prntscr.com/1vqyjkd I tried to re-install both "Profile Switcher" and Connector but no luck. Has anybody fixed that issue?

about:profiles
rename your default profile to any name you like and it will work (I just tried it)

**Comment by null-dev** [comment]
Closing this issue, if you are still having problems with installation, please open another issue with your system details.

Also, I've added installation instructions for Linux Flatpak users in the latest release.
